name: yavalinux
services:
  build_packages:
    network_mode: host
    build: .
    deploy:
      mode: global-job
    volumes:
      - ./:/yavalinux
    entrypoint: /yavalinux/build.sh
  build_aur_packages:
    network_mode: host
    build: .
    deploy:
      mode: global-job
    volumes:
      - ./:/yavalinux
    entrypoint: /yavalinux/build_aur.sh
